source("[01]load data from parquet into duckdb.R")
source("[01b]vascular_pvl_clean.R")
source("[01c]cci_calculation.R")
source("[02a]derived_conditions.R")
source("[02b]derived_procedures.R")
source("[02c]derived_medication_tables.R")
source("[02d]derived_lab_tables.R")
source("[02e]derived_sdoh_tables.R")
source("[03]vascular_patient_summary.R")
source("[04]outlier_screen.R")
source("[05]clean_rollup.R")
rm(list = ls())
gc()
source("[06]feature_supplemental.R")
rm(list = ls())
gc()
source("[07]treatment_model.R")
rm(list = ls())
gc()
source("[08]amputation_model.R")
rm(list = ls())
gc()
source("[09]death_model.R")
rm(list = ls())
gc()
source("[10]analysis_summary.R")